package directus

import (
	"bytes"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/textproto"
	"path/filepath"
	"strings"
)

// ClearCache flushes the Directus cache. When system is true the schema/system
// cache is cleared as well.
func (c *Client) ClearCache(system bool) error {
	path := "/utils/cache/clear"
	if system {
		path = "/utils/cache/clear?system"
	}
	return c.execute("POST", path, nil, nil)
}

// RandomString returns a random string generated by the server. When length is
// greater than zero it is passed through as the requested length.
func (c *Client) RandomString(length int) (string, error) {
	path := "/utils/random/string"
	if length > 0 {
		path = fmt.Sprintf("/utils/random/string?length=%d", length)
	}
	return request[string](c, "GET", path, nil, nil)
}

// UtilitySort moves an item within a sortable collection so that it sits at the
// position currently held by another item.
func (c *Client) UtilitySort(collection string, item, to any) error {
	if collection == "" {
		return fmt.Errorf("collection must be provided")
	}
	body := map[string]any{
		"item": item,
		"to":   to,
	}
	return c.execute("POST", fmt.Sprintf("/utils/sort/%s", collection), nil, body)
}

// UtilsExport starts an asynchronous export of a collection in the given format.
func (c *Client) UtilsExport(collection, format string, query map[string]any, file map[string]any) error {
	if collection == "" || format == "" {
		return fmt.Errorf("collection and format must be provided")
	}
	body := map[string]any{
		"format": format,
		"query":  query,
		"file":   file,
	}
	return c.execute("POST", fmt.Sprintf("/utils/export/%s", collection), nil, body)
}

// UtilsImport imports a file's contents into the given collection. The request
// is sent as multipart/form-data with a single "file" part. This is the only
// endpoint that builds its own request to set the multipart boundary.
func (c *Client) UtilsImport(collection string, data io.Reader, filename string) error {
	if collection == "" {
		return fmt.Errorf("collection must be provided")
	}
	if data == nil {
		return fmt.Errorf("data must be provided")
	}
	if filename == "" {
		return fmt.Errorf("filename must be provided")
	}

	var buf bytes.Buffer
	writer := multipart.NewWriter(&buf)

	// Directus validates the file part's media type, so set it from the
	// filename extension instead of the default application/octet-stream.
	contentType := "application/octet-stream"
	switch strings.ToLower(filepath.Ext(filename)) {
	case ".json":
		contentType = "application/json"
	case ".csv":
		contentType = "text/csv"
	case ".xml":
		contentType = "text/xml"
	case ".yaml", ".yml":
		contentType = "text/yaml"
	}
	header := textproto.MIMEHeader{}
	header.Set("Content-Disposition", fmt.Sprintf(`form-data; name="file"; filename="%s"`, filename))
	header.Set("Content-Type", contentType)
	part, err := writer.CreatePart(header)
	if err != nil {
		return err
	}
	if _, err := io.Copy(part, data); err != nil {
		return err
	}
	if err := writer.Close(); err != nil {
		return err
	}

	req, err := http.NewRequest("POST", buildURL(c.HostURL, fmt.Sprintf("/utils/import/%s", collection), nil), &buf)
	if err != nil {
		return err
	}
	req.Header.Set("Content-Type", writer.FormDataContentType())

	_, err = c.doRequest(req)
	return err
}
